CREATE SCHEMA HANDBALL;

CREATE TABLE HANDBALL.COMPETITION (
		COMPETITION_ID NUMBER NOT NULL AUTO_INCREMENT,
		NAME VARCHAR2(100) NOT NULL
	);

ALTER TABLE HANDBALL.COMPETITION ADD CONSTRAINT COMPETITION_PK PRIMARY KEY (COMPETITION_ID);
